project_id = "nehmmvtpagncmldivnxn"

[functions.discover-endpoints]
verify_jwt = false

[functions.fetch-players]
verify_jwt = false

[functions.pixbingo-proxy]
verify_jwt = false

[functions.manage-users]
verify_jwt = false

[functions.process-campaign]
verify_jwt = false

[functions.auto-process-campaigns]
verify_jwt = false

[functions.popup-check]
verify_jwt = false

[functions.player-profile]
verify_jwt = false

[functions.popup-event]
verify_jwt = false

[functions.process-cashback]
verify_jwt = false

[functions.gamification-widget]
verify_jwt = false

[functions.sync-mission-progress]
verify_jwt = false

[functions.sync-tournament-scores]
verify_jwt = false
