project_id = "urxbuiuwasvxwxuythzc"

[functions.discover-endpoints]
verify_jwt = false

[functions.fetch-players]
verify_jwt = false

[functions.pixbingo-proxy]
verify_jwt = false

[functions.manage-users]
verify_jwt = false

[functions.process-campaign]
verify_jwt = false

[functions.auto-process-campaigns]
verify_jwt = false

[functions.popup-check]
verify_jwt = false
